// Configuring Vite https://vitejs.dev/config/

export const setting = {
    base: '/',
    publicDir: 'public',
    cacheDir: 'node_modules/.vite',
    outDir: 'dist',
    assetsDir: 'static/',
    sourcemap: false,
    chunkSizeWarningLimit: 2000,
    cssCodeSplit: true,
    brotliSize: false,
    host: '0.0.0.0',
    port: '5173',
    strictPort: false,
    open: true,
    progressBar: true,
    defaultOpeneds: ['/permission'],
    uniqueOpened: false,
    tokenName: 'accessToken',
    loginInterception: true,
    tokenTableName: 'access-token',
    langKey: 'i18nLang',
    lang: 'zh-tw',
    storage: 'localStorage',
    title: 'Fashion Store',
    copyright: '© Fashion Store',
    footerCopyright: true,
    keepAliveMaxNum: 99,
    recordRoute: true,
    routesWhiteList: ['/login', '/404', '/401'],
    debounce: [],
    extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
    logLevel: 'info',
    clearScreen: false,
    drop_console: true,
    drop_debugger: true,
}
